# Generated by Django 4.2 on 2023-04-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
            ],
        ),
    ]
