# Generated by Django 4.2 on 2023-04-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookstore_coupons_payments_watchlist_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='books',
            field=models.ManyToManyField(to='books.books'),
        ),
    ]
