# Generated by Django 4.2 on 2023-04-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_reviews_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
    ]
